---
version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.7.1

commands:
  restore-docker:
    description: Restore Docker image cache
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - restore_cache:
          key: v1-{{.Branch}}
      - run:
          name: Restore Docker image cache
          command: docker load -i /cache/docker.tar

jobs:
  # Build and test the Docker image
  build-docker:
    docker:
      - image: docker:stable-git

    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Build Docker image
          command: docker build -t app:build .

      - run:
          name: Test Code
          command: docker run app:build /app/bin/run_tests.sh

      - run:
          name: docker save app:build
          command: mkdir -p /cache; docker save -o /cache/docker.tar "app:build"

      - save_cache:
          key: v1-{{ .Branch }}-{{epoch}}
          paths:
            - /cache/docker.tar

  # Test and lint the Python library in supported Python environments
  test-library-36:
    docker:
      - image: circleci/python:3.6-buster
    steps:
      - checkout

      - run:
          name: Install requirements
          command: pip install -r requirements.dev.txt

      - run:
          name: Test and lint
          command: tox -e py36,py36-lint

  test-library-37:
    docker:
      - image: circleci/python:3.7-buster
    steps:
      - checkout

      - run:
          name: Install requirements
          command: pip install -r requirements.dev.txt

      - run:
          name: Test
          command: tox -e py37

  test-library-38:
    docker:
      - image: circleci/python:3.8-buster
    steps:
      - checkout

      - run:
          name: Install requirements
          command: pip install -r requirements.dev.txt

      - run:
          name: Test
          command: tox -e py38

  test-library-39:
    docker:
      - image: circleci/python:3.9-buster
    steps:
      - checkout

      - run:
          name: Install requirements
          command: pip install -r requirements.dev.txt

      - run:
          name: Test
          command: tox -e py39

workflows:
  version: 2
  main:
    jobs:
      - build-docker

      - test-library-36

      - test-library-37

      - test-library-38

      - test-library-39

#       - gcp-gcr/build-and-push-image:
#           # See https://bugzilla.mozilla.org/show_bug.cgi?id=1608957 for
#           # details
#           context: data-eng-airflow-gcr
#           image: fx-crash-sig
#           requires:
#             - test
#             - lint
#           filters:
#             branches:
#               only: master
