---
version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.7.1

commands:
  restore-docker:
    description: Restore Docker image cache
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - restore_cache:
          key: v1-{{.Branch}}
      - run:
          name: Restore Docker image cache
          command: docker load -i /cache/docker.tar

jobs:
  # Build and test the Docker image
  build-docker:
    docker:
      - image: docker:stable-git

    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Build Docker image
          command: docker build -t app:build .

      - run:
          name: Test Code
          command: docker run app:build /app/bin/run_tests.sh

      - run:
          name: docker save app:build
          command: mkdir -p /cache; docker save -o /cache/docker.tar "app:build"

      - save_cache:
          key: v1-{{ .Branch }}-{{epoch}}
          paths:
            - /cache/docker.tar

  # Test and lint the Python library in supported Python environments
  #
  # NOTE(willkg): This doesn't test >=3.9 because themattrix/tox doesn't
  # support that, yet: https://github.com/themattrix/docker-tox/issues/22
  test-library:
    docker:
      - image: themattrix/tox

    steps:
      - checkout

      - run:
          name: Install requirements
          command: pip install -r requirements.dev.txt

      - run:
          name: Test
          command: tox -e py36,py37,py38

      - run:
          name: Lint
          command: bin/run_lint.sh

workflows:
  version: 2
  main:
    jobs:
      - build-docker

      - test-library

#       - gcp-gcr/build-and-push-image:
#           # See https://bugzilla.mozilla.org/show_bug.cgi?id=1608957 for
#           # details
#           context: data-eng-airflow-gcr
#           image: fx-crash-sig
#           requires:
#             - test
#             - lint
#           filters:
#             branches:
#               only: master
